# Generated by Django 5.2.5 on 2025-10-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_created_at_user_is_verified_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('operator', 'Operador'), ('supervisor', 'Supervisor'), ('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('control', 'Control de calidad')], default='operator', max_length=50, null=True),
        ),
    ]
