# Generated by Django 5.2.5 on 2025-08-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del componente')),
                ('comp_id', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('component_type', models.CharField(choices=[('fabricated', 'Fabricado'), ('purchased', 'Comprado')], default='purchased', max_length=20, verbose_name='Tipo de componente')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_value', models.CharField(max_length=100, verbose_name='Orden de Producción')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre producto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('status', models.IntegerField(choices=[(0, 'No iniciado'), (25, '25% Completado'), (50, '50% Completado'), (75, '75% Completado'), (100, '100% Completado')], default=0, verbose_name='Estado de producción')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad de productos a fabricar')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('components', models.ManyToManyField(to='products.component', verbose_name='Componentes')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-priority', 'op_value'],
            },
        ),
    ]
