# Generated by Django 5.2.5 on 2025-08-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('cutting', 'Corte'), ('welding', 'Soldadura'), ('assembly', 'Ensamblaje'), ('painting', 'Pintura'), ('testing', 'Pruebas')], default='assembly', max_length=40, verbose_name='Tipo de proceso')),
                ('process_source', models.CharField(choices=[('internal', 'Interno'), ('external', 'Externalizado')], default='internal', max_length=20, verbose_name='Origen del proceso')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'ordering': ['process_type'],
            },
        ),
        migrations.AddField(
            model_name='component',
            name='manufacturing_process',
            field=models.ManyToManyField(to='products.process', verbose_name='Proceso de manufactura'),
        ),
    ]
