# Generated by Django 5.2.5 on 2025-08-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_process_component_manufacturing_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='process',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='process',
            name='updated_at',
        ),
    ]
