# Generated by Django 5.2.5 on 2025-08-27 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_process_end_time_remove_process_start_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre maquina')),
                ('machine_type', models.CharField(choices=[('lathe', 'Torno'), ('milling', 'Fresado'), ('welding', 'Soldadora'), ('painting', 'Pintura'), ('packing', 'Embalaje'), ('assembly', 'Montaje')], default='lathe', max_length=50, verbose_name='Tipo de maquina')),
                ('state', models.CharField(choices=[('free', 'Libre'), ('busy', 'Ocupada'), ('in_preparation', 'En preparación')], default='free', max_length=50, verbose_name='Estado actual')),
            ],
            options={
                'verbose_name': 'Maquina',
                'verbose_name_plural': 'Maquinas',
                'ordering': ['machine_type'],
            },
        ),
        migrations.AddField(
            model_name='process',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='process',
            name='machine_assigned',
            field=models.ManyToManyField(to='products.machine', verbose_name='Maquina'),
        ),
    ]
