# Generated by Django 5.2.5 on 2025-08-27 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_machine_process_assigned_to_process_machine_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='machine_assigned',
            new_name='machine',
        ),
    ]
