# Generated by Django 5.2.5 on 2025-08-27 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_machine_assigned_process_machine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='machine',
            new_name='machine_asigned',
        ),
    ]
