# Generated by Django 5.2.5 on 2025-08-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_machine_process_machine_asigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='machine_asigned',
        ),
        migrations.AddField(
            model_name='process',
            name='machines',
            field=models.ManyToManyField(to='products.machine', verbose_name='Maquinas'),
        ),
        migrations.AddField(
            model_name='process',
            name='name',
            field=models.CharField(default='Proceso', max_length=100, verbose_name='Nombre del proceso'),
        ),
    ]
